version: '3.9'
services:
  qanterium:
    container_name: qanterium_container
    image: yelpinger/qanterium:1.0.0
    restart: always
    ports:
      - '431:8080'
    environment:
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_FILE_NAME: /logs/qanterium/qanterium.log
      LOGGING_LOGBACK_ROLLINGPOLICY_MAX_FILE_SIZE: 5MB
      LOGGING_LOGBACK_ROLLINGPOLICY_MAX_HISTORY: 5
      LOGGING_LOGBACK_ROLLINGPOLICY_TOTAL_SIZE_CAP: 20MB

      SPRING_LIQUIBASE_CHANGE_LOG: classpath:/db/changelog/changelog-master.xml
      SPRING_LIQUIBASE_ENABLED: true
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_container:5432/qanterium
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_SHOW_SQL_ENABLED: false
      SPRING_JPA_OPEN_IN_VIEW_ENABLED: false
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate

      QANTERIUM_SECURITY_JWT_TIME_TO_LIVE: 600000
      QANTERIUM_EXCHANGE_MAX_IN_MEMORY_SIZE_MB: 10
      QANTERIUM_EXCHANGE_EXTERNAL_API_URL: https://v6.exchangerate-api.com
      QANTERIUM_EXCHANGE_EXTERNAL_API_API_KEY: 000000000000000000
      QANTERIUM_EXCHANGE_EXTERNAL_API_SSL_TRUSTSTORE_PATH: classpath:certs/external_api_truststore.jks
      QANTERIUM_EXCHANGE_EXTERNAL_API_SSL_TRUSTSTORE_PASSWORD: 123456
      QANTERIUM_EXCHANGE_EXTERNAL_API_SSL_MUTUAL_ENABLED: false
      QANTERIUM_EXCHANGE_EXTERNAL_API_SSL_MUTUAL_KEYSTORE_PATH:
      QANTERIUM_EXCHANGE_EXTERNAL_API_SSL_MUTUAL_KEYSTORE_PASSWORD:
      QANTERIUM_EXCHANGE_EXTERNAL_API_SSL_MUTUAL_KEYSTORE_SECRETKEY:
      QANTERIUM_EXCHANGE_EXTERNAL_API_SSL_PROTOCOL: TLSv1.2
      QANTERIUM_EXCHANGE_NBG_URL: https://nbg.gov.ge/gw/api/ct/monetarypolicy
      QANTERIUM_EXCHANGE_NBG_SSL_TRUSTSTORE_PATH: classpath:certs/nbg_truststore.jks
      QANTERIUM_EXCHANGE_NBG_SSL_PASSWORD: QwsaDE231
      QANTERIUM_EXCHANGE_NBG_SSL_MUTUAL_ENABLED: false
      QANTERIUM_EXCHANGE_NBG_SSL_MUTUAL_KEYSTORE_PATH:
      QANTERIUM_EXCHANGE_NBG_SSL_MUTUAL_KEYSTORE_PASSWORD:
      QANTERIUM_EXCHANGE_NBG_SSL_MUTUAL_SECRETKEY:
      QANTERIUM_EXCHANGE_NBG_SSL_PROTOCOL: TLSv1.2


    volumes:
      - ./docker_data/logs/qanterium:/logs/qanterium