logging:
  level:
    root: info
  file:
    name: C:/logs/qanterion/qanterion.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 5
      total-size-cap: 20MB

spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/qanterion
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      connectionTimeout: 30000
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

qanterium:
  security:
    jwt:
      time-to-live: 600000
  exchange:
    max-in-memory-size-mb: 10
    external-api:
      url: https://v6.exchangerate-api.com/v6/
      api-key: 0000000000000000
      ssl:
        trust-store:
          path: classpath:certs/external_api_truststore.jks
          password: "123456"
        mutual:
          enabled: false
          key-store:
            path:
            password:
            secret-key:
      protocol: TLSv1.2
    nbg:
      url: https://nbg.gov.ge/gw/api/ct/monetarypolicy
      ssl:
        trust-store:
          path: classpath:certs/nbg_truststore.jks
          password: "QwsaDE231"
        mutual:
          enabled: false
          key-store:
            path:
            password:
            secret-key:
      protocol: TLSv1.2